package clasesjava;
// Generated 16-abr-2020 17:36:16 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Articulo generated by hbm2java
 */
public class Articulo  implements java.io.Serializable {


     private Integer idArticulo;
     private String nombreArticulo;
     private int codigobarras;
     private BigDecimal precioVenta;
     private int cantidadStock;
     private int proveedor;
     private String descripcion;
     private Proveedor proveedors;

    public Articulo() {
    }

	
    public Articulo(String nombreArticulo, int codigobarras, BigDecimal precioVenta, int cantidadStock, int proveedor, String descripcion) {
        this.nombreArticulo = nombreArticulo;
        this.codigobarras = codigobarras;
        this.precioVenta = precioVenta;
        this.cantidadStock = cantidadStock;
        this.proveedor = proveedor;
        this.descripcion = descripcion;
    }
    public Articulo(String nombreArticulo, int codigobarras, BigDecimal precioVenta, int cantidadStock, int proveedor, String descripcion, Proveedor proveedors) {
       this.nombreArticulo = nombreArticulo;
       this.codigobarras = codigobarras;
       this.precioVenta = precioVenta;
       this.cantidadStock = cantidadStock;
       this.proveedor = proveedor;
       this.descripcion = descripcion;
       this.proveedors = proveedors;
    }
   
    public Integer getIdArticulo() {
        return this.idArticulo;
    }
    
    public void setIdArticulo(Integer idArticulo) {
        this.idArticulo = idArticulo;
    }
    public String getNombreArticulo() {
        return this.nombreArticulo;
    }
    
    public void setNombreArticulo(String nombreArticulo) {
        this.nombreArticulo = nombreArticulo;
    }
    public int getCodigobarras() {
        return this.codigobarras;
    }
    
    public void setCodigobarras(int codigobarras) {
        this.codigobarras = codigobarras;
    }
    public BigDecimal getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(BigDecimal precioVenta) {
        this.precioVenta = precioVenta;
    }
    public int getCantidadStock() {
        return this.cantidadStock;
    }
    
    public void setCantidadStock(int cantidadStock) {
        this.cantidadStock = cantidadStock;
    }
    public int getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(int proveedor) {
        this.proveedor = proveedor;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Proveedor getProveedors() {
        return this.proveedors;
    }
    
    public void setProveedor(Proveedor proveedors) {
        this.proveedors = proveedors;
    }




}


