package clasesjava;
// Generated 16-abr-2020 17:36:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private int codigoEmpleado;
     private String dniNie;
     private String nombre;
     private String apellidos;
     private String email;
     private int codigoJefe;
     private String puesto;
     private Set clientes = new HashSet(0);
     private Login login;

    public Empleado() {
    }

	
    public Empleado(int codigoEmpleado, String dniNie, String nombre, String apellidos, int codigoJefe, String puesto) {
        this.codigoEmpleado = codigoEmpleado;
        this.dniNie = dniNie;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.codigoJefe = codigoJefe;
        this.puesto = puesto;
    }
    public Empleado(int codigoEmpleado, String dniNie, String nombre, String apellidos, String email, int codigoJefe, String puesto, Set clientes, Login login) {
       this.codigoEmpleado = codigoEmpleado;
       this.dniNie = dniNie;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.email = email;
       this.codigoJefe = codigoJefe;
       this.puesto = puesto;
       this.clientes = clientes;
       this.login = login;
    }
   
    public int getCodigoEmpleado() {
        return this.codigoEmpleado;
    }
    
    public void setCodigoEmpleado(int codigoEmpleado) {
        this.codigoEmpleado = codigoEmpleado;
    }
    public String getDniNie() {
        return this.dniNie;
    }
    
    public void setDniNie(String dniNie) {
        this.dniNie = dniNie;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getCodigoJefe() {
        return this.codigoJefe;
    }
    
    public void setCodigoJefe(int codigoJefe) {
        this.codigoJefe = codigoJefe;
    }
    public String getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }
    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }




}


