package clasesjava;
// Generated 16-abr-2020 17:36:16 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private Integer idProveedor;
     private Articulo articulo;
     private String nombreProveedor;
     private String cifProveedor;
     private String direccionProveedor;
     private String telefonoProveedor;
     private String pais;
     private String provincia;
     private String ciudad;
     private String productos;
     private BigDecimal precioProveedor;
     private BigDecimal cantidadStock;

    public Proveedor() {
    }

    public Proveedor(Articulo articulo, String nombreProveedor, String cifProveedor, String direccionProveedor, String telefonoProveedor, String pais, String provincia, String ciudad, String productos, BigDecimal precioProveedor, BigDecimal cantidadStock) {
       this.articulo = articulo;
       this.nombreProveedor = nombreProveedor;
       this.cifProveedor = cifProveedor;
       this.direccionProveedor = direccionProveedor;
       this.telefonoProveedor = telefonoProveedor;
       this.pais = pais;
       this.provincia = provincia;
       this.ciudad = ciudad;
       this.productos = productos;
       this.precioProveedor = precioProveedor;
       this.cantidadStock = cantidadStock;
    }
   
    public Integer getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public String getNombreProveedor() {
        return this.nombreProveedor;
    }
    
    public void setNombreProveedor(String nombreProveedor) {
        this.nombreProveedor = nombreProveedor;
    }
    public String getCifProveedor() {
        return this.cifProveedor;
    }
    
    public void setCifProveedor(String cifProveedor) {
        this.cifProveedor = cifProveedor;
    }
    public String getDireccionProveedor() {
        return this.direccionProveedor;
    }
    
    public void setDireccionProveedor(String direccionProveedor) {
        this.direccionProveedor = direccionProveedor;
    }
    public String getTelefonoProveedor() {
        return this.telefonoProveedor;
    }
    
    public void setTelefonoProveedor(String telefonoProveedor) {
        this.telefonoProveedor = telefonoProveedor;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getProductos() {
        return this.productos;
    }
    
    public void setProductos(String productos) {
        this.productos = productos;
    }
    public BigDecimal getPrecioProveedor() {
        return this.precioProveedor;
    }
    
    public void setPrecioProveedor(BigDecimal precioProveedor) {
        this.precioProveedor = precioProveedor;
    }
    public BigDecimal getCantidadStock() {
        return this.cantidadStock;
    }
    
    public void setCantidadStock(BigDecimal cantidadStock) {
        this.cantidadStock = cantidadStock;
    }




}


