package provinciasCiudades;
// Generated 13-abr-2020 16:26:50 by Hibernate Tools 4.3.1



/**
 * Municipios generated by hbm2java
 */
public class Municipios  implements java.io.Serializable {


     private long idMunicipios;
     private int provincias;
     private String municipio;

    public Municipios() {
    }

    public Municipios(long idMunicipios, int provincias, String municipio) {
       this.idMunicipios = idMunicipios;
       this.provincias = provincias;
       this.municipio = municipio;
    }
   
    public long getIdMunicipios() {
        return this.idMunicipios;
    }
    
    public void setIdMunicipios(long idMunicipios) {
        this.idMunicipios = idMunicipios;
    }
    public int getProvincias() {
        return this.provincias;
    }
    
    public void setProvincias(int provincias) {
        this.provincias = provincias;
    }
    public String getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }

    @Override
    public String toString() {
        return  municipio ;
    }

}


